### Supervised Learning using Synthetic DataSet

###### Packages used     1)pandas     2)numpy     3)scipy     4)scikit-learn       1st step importing Files to Pandas Data Frame. Pandas dataframe gives lot of features to manipulate data without writing SQL Queries. Creating 2 dataframes  1) Train 2) Test

In [1]:
import os,fnmatch
import csv
import pandas as pd

train_file = "/usr/bin/MachineLearning/WestNileVirusPrediction/codetest_train.txt"
test_file = "/usr/bin/MachineLearning/WestNileVirusPrediction/codetest_test.txt"

credit_card_dataframe = pd.read_csv(train_file,sep='\t')
credit_card_testframe= pd.read_csv(test_file,sep='\t')

In [2]:
credit_card_dataframe.head()

,target,f_0,f_1,f_2,f_3,f_4,f_5,f_6,f_7,f_8,...,f_244,f_245,f_246,f_247,f_248,f_249,f_250,f_251,f_252,f_253
0,3.066056,-0.652557,0.255256,-0.615412,-1.833283,-0.735654,NaN,1.115108,-0.170707,-0.350879,...,-1.607174,-1.400451,-0.920319,-0.198487,-0.944919,-0.572555,0.170449,-0.417764,-1.244350,-0.502889
1,-1.910473,1.178667,-0.093398,-0.555568,0.811153,-0.467931,-0.005488,-0.116258,-1.242854,1.984955,...,1.281957,0.032356,-0.060830,NaN,-0.061294,-0.301641,1.280799,-0.849742,0.821387,-0.259742
2,7.830711,0.180984,-0.778108,-0.919190,0.112607,0.887144,-0.761681,1.872443,-1.708934,0.134782,...,-0.236893,-0.659965,1.072506,-0.192872,0.570371,-0.267201,1.434515,1.331823,-1.146947,2.579905
3,-2.180862,0.745228,-0.245268,-1.343348,1.163072,-0.168847,-0.150516,-1.099532,0.225346,1.223015,...,0.709195,-0.203496,-0.135737,-0.570835,1.682078,0.243042,-0.380941,0.612880,1.032715,0.400305
4,5.462784,1.217383,-1.323946,-0.958151,0.448290,-2.873187,-0.855653,0.602568,0.763372,0.019770,...,0.892303,-0.432659,-0.877101,0.289258,0.653759,1.230144,0.456956,-0.754051,-0.025100,-0.931225

In [3]:
credit_card_testframe.head()

,f_0,f_1,f_2,f_3,f_4,f_5,f_6,f_7,f_8,f_9,...,f_244,f_245,f_246,f_247,f_248,f_249,f_250,f_251,f_252,f_253
0,1.122161,2.372084,-1.302713,-0.420838,-1.723640,0.205672,0.448599,1.305198,-0.343860,0.307042,...,0.987785,-0.472495,0.521588,-0.307917,1.061505,-0.839408,0.818555,0.341522,-0.162471,-1.122791
1,0.644808,-0.817831,-1.193122,0.285867,0.946388,2.001413,-1.490880,-0.162357,-1.668155,0.309635,...,-0.019666,0.763533,-0.622877,0.147480,0.391625,0.509444,1.608021,-0.320951,-1.723378,1.222700
2,-0.661031,0.372804,1.160255,0.447586,NaN,-0.377757,-0.644618,0.713097,1.900375,0.627264,...,0.156354,-0.267040,0.139786,-0.907847,0.093219,0.226585,-0.995615,-0.665005,0.444115,-1.452071
3,0.837063,1.269625,-1.420543,-0.482877,1.136028,0.051415,-0.096677,NaN,-1.524041,-0.252841,...,1.653141,1.950726,0.656887,-1.237622,-0.487024,-1.340936,1.221345,1.938266,-0.447294,0.410684
4,-0.001493,-0.050440,0.441970,0.229519,0.524835,0.326089,-0.589504,-0.287145,-0.555982,-0.088494,...,-0.290987,-0.195876,-0.737650,-0.377331,-0.660202,1.775678,-1.027535,-0.796754,0.184635,0.378488

In [4]:
pd.set_option('display.max_rows', 300)
pd.set_option('display.max_columns', 20)
credit_card_testframe.dtypes

f_0      float64
f_1      float64
f_2      float64
f_3      float64
f_4      float64
f_5      float64
f_6      float64
f_7      float64
f_8      float64
f_9      float64
f_10     float64
f_11     float64
f_12     float64
f_13     float64
f_14     float64
f_15     float64
f_16     float64
f_17     float64
f_18     float64
f_19     float64
f_20     float64
f_21     float64
f_22     float64
f_23     float64
f_24     float64
f_25     float64
f_26     float64
f_27     float64
f_28     float64
f_29     float64
f_30     float64
f_31     float64
f_32     float64
f_33     float64
f_34     float64
f_35     float64
f_36     float64
f_37     float64
f_38     float64
f_39     float64
f_40     float64
f_41     float64
f_42     float64
f_43     float64
f_44     float64
f_45     float64
f_46     float64
f_47     float64
f_48     float64
f_49     float64
f_50     float64
f_51     float64
f_52     float64
f_53     float64
f_54     float64
f_55     float64
f_56     float64
f_57     float64
f_58     float64
f_59     float64
f_60     float64
f_61      object
f_62     float64
f_63     float64
f_64     float64
f_65     float64
f_66     float64
f_67     float64
f_68     float64
f_69     float64
f_70     float64
f_71     float64
f_72     float64
f_73     float64
f_74     float64
f_75     float64
f_76     float64
f_77     float64
f_78     float64
f_79     float64
f_80     float64
f_81     float64
f_82     float64
f_83     float64
f_84     float64
f_85     float64
f_86     float64
f_87     float64
f_88     float64
f_89     float64
f_90     float64
f_91     float64
f_92     float64
f_93     float64
f_94     float64
f_95     float64
f_96     float64
f_97     float64
f_98     float64
f_99     float64
f_100    float64
f_101    float64
f_102    float64
f_103    float64
f_104    float64
f_105    float64
f_106    float64
f_107    float64
f_108    float64
f_109    float64
f_110    float64
f_111    float64
f_112    float64
f_113    float64
f_114    float64
f_115    float64
f_116    float64
f_117    float64
f_118    float64
f_119    float64
f_120    float64
f_121     object
f_122    float64
f_123    float64
f_124    float64
f_125    float64
f_126    float64
f_127    float64
f_128    float64
f_129    float64
f_130    float64
f_131    float64
f_132    float64
f_133    float64
f_134    float64
f_135    float64
f_136    float64
f_137    float64
f_138    float64
f_139    float64
f_140    float64
f_141    float64
f_142    float64
f_143    float64
f_144    float64
f_145    float64
f_146    float64
f_147    float64
f_148    float64
f_149    float64
f_150    float64
f_151    float64
f_152    float64
f_153    float64
f_154    float64
f_155    float64
f_156    float64
f_157    float64
f_158    float64
f_159    float64
f_160    float64
f_161    float64
f_162    float64
f_163    float64
f_164    float64
f_165    float64
f_166    float64
f_167    float64
f_168    float64
f_169    float64
f_170    float64
f_171    float64
f_172    float64
f_173    float64
f_174    float64
f_175    float64
f_176    float64
f_177    float64
f_178    float64
f_179    float64
f_180    float64
f_181    float64
f_182    float64
f_183    float64
f_184    float64
f_185    float64
f_186    float64
f_187    float64
f_188    float64
f_189    float64
f_190    float64
f_191    float64
f_192    float64
f_193    float64
f_194    float64
f_195    float64
f_196    float64
f_197    float64
f_198    float64
f_199    float64
f_200    float64
f_201    float64
f_202    float64
f_203    float64
f_204    float64
f_205    float64
f_206    float64
f_207    float64
f_208    float64
f_209    float64
f_210    float64
f_211    float64
f_212    float64
f_213    float64
f_214    float64
f_215     object
f_216    float64
f_217    float64
f_218    float64
f_219    float64
f_220    float64
f_221    float64
f_222    float64
f_223    float64
f_224    float64
f_225    float64
f_226    float64
f_227    float64
f_228    float64
f_229    float64
f_230    float64
f_231    float64
f_232    float64
f_233    float64
f_234    float64
f_235    float64
f_236    float64
f_237     object
f_238    float64
f_239    float64
f_240    float64
f_241    float64
f_242    float64
f_243    float64
f_244    float64
f_245    float64
f_246    float64
f_247    float64
f_248    float64
f_249    float64
f_250    float64
f_251    float64
f_252    float64
f_253    float64
Length: 254, dtype: object

#### There are 4 categorical Variables f_61,f_121,f215,and f237 in the Training Data Frame. Categorical variables have to be converted to dummy variables to be passed as input to Supervised Learning Algorithm. I am using Pandas getdummies method to convert it.

In [12]:
credit_card_dataframe['f_61'].unique()

array(['b', 'a', 'd', 'c', nan, 'e'], dtype=object)

In [13]:
credit_card_testframe['f_61'].unique()

array(['e', 'd', 'b', 'a', 'c', nan], dtype=object)

In [14]:
credit_card_dataframe['f_121'].unique()

array(['D', 'A', 'B', 'C', 'E', 'F', nan], dtype=object)

In [15]:
credit_card_dataframe['f_215'].unique()

array(['red', 'blue', 'orange', 'yellow', nan], dtype=object)

In [16]:
credit_card_dataframe['f_237'].unique()

array(['Canada', 'USA', 'Mexico', nan], dtype=object)

In [2]:
credit_card_dataframe.describe()

,target,f_0,f_1,f_2,f_3,f_4,f_5,f_6,f_7,f_8,...,f_244,f_245,f_246,f_247,f_248,f_249,f_250,f_251,f_252,f_253
count,5000.000000,4903.000000,4928.000000,4908.000000,4910.000000,4907.000000,4912.000000,4897.000000,4904.000000,4893.000000,...,4910.000000,4883.000000,4914.000000,4894.000000,4902.000000,4886.000000,4900.000000,4921.000000,4904.000000,4904.000000
mean,1.143878,-0.000432,0.002564,0.028875,-0.005436,-0.006764,0.005568,0.001536,-0.001016,0.009748,...,0.013529,0.004937,0.023262,-0.018450,-0.009832,0.016954,-0.004944,0.016878,-0.001356,0.010331
std,5.259896,0.999737,0.997931,1.019343,0.990349,1.006289,0.995800,1.004624,0.997360,0.988310,...,1.001454,0.997329,0.996465,1.005001,0.989225,1.011337,0.991580,1.001362,1.003412,1.006887
min,-26.705570,-3.940976,-3.847382,-3.818473,-3.434423,-3.400202,-4.051005,-3.179496,-3.889719,-3.856546,...,-3.585086,-3.493958,-3.484578,-4.012033,-3.252239,-3.821459,-3.376073,-3.373395,-3.949648,-3.727771
25%,-2.034383,-0.673040,-0.684705,-0.650854,-0.654998,-0.685200,-0.659947,-0.671828,-0.679356,-0.662404,...,-0.666017,-0.676178,-0.661783,-0.692160,-0.662535,-0.647772,-0.679635,-0.647463,-0.695102,-0.676679
50%,1.166835,-0.010543,-0.002652,0.047116,0.003579,-0.007036,-0.007822,-0.003055,-0.021591,0.016544,...,0.025606,-0.027898,0.026912,-0.034966,-0.010708,0.002441,0.009770,0.019531,0.002471,0.015306
75%,4.439549,0.677278,0.674600,0.718753,0.667814,0.653662,0.648748,0.678594,0.670028,0.698020,...,0.671749,0.670035,0.702553,0.655212,0.650979,0.709693,0.660469,0.692202,0.672384,0.705512
max,26.347818,3.830801,3.995597,3.198775,4.962191,3.106121,4.295765,4.165960,3.798185,4.195049,...,3.365021,3.455789,3.881038,3.689781,3.629413,4.144275,3.873226,3.186501,3.724332,3.955565

In [11]:
 %matplotlib inline

###### I like to Plot and See distribution of data in the Dataset. I prefer Histogram to see the distribution. All the columns had some sort of normal distribution of data, so i dont think I need to do any Data Transformation like applying log, SQRT, Square, cube etc.  I commented the below section of code since i plotted all 253 columns to see the distribution, ipython notebook with all the images was getting really big to open.

In [ ]:
#Plotting to see the distribution of data
#since the columns are anonymized, i am plotting all the columns to see the data distribution
#1st step in any data analysis is to plot and see the distribution of data
#credit_card_dataframe['f_0'].plot(kind='hist')
#credit_card_dataframe['f_1'].plot(kind='hist')
#credit_card_dataframe['f_2'].plot(kind='hist')
#credit_card_dataframe['f_3'].plot(kind='hist')

In [18]:
#Handling missing categorical variables with mode
credit_card_dataframe['f_61'].describe()

count     4905
unique       5
top          d
freq      1015
Name: f_61, dtype: object

###### Missing values have to be handled before dataset is passed as input to Machine learning algorithms. for Categorical variable i prefer to use "Mode" method to fill the missing values. For f_61 most occuring value was 'd' hence used that to fill the missing values. Followed the same approach for f_121, f_215, and f_237 columns too.  Whatever data transformation function done on Training Data set should be applied in Test DataSet too. Hence applying it to credit_card_testframe

In [3]:
credit_card_dataframe['f_61'] = credit_card_dataframe['f_61'].fillna('d')
credit_card_testframe['f_61'] = credit_card_testframe['f_61'].fillna('d')
credit_card_dataframe['f_61'].unique()
credit_card_testframe['f_61'].unique()

array(['e', 'd', 'b', 'a', 'c'], dtype=object)

In [20]:
#Handling missing categorical variables with mode
credit_card_dataframe['f_121'].describe()

count     4914
unique       6
top          B
freq       837
Name: f_121, dtype: object

In [21]:
credit_card_dataframe['f_121'].unique()

array(['D', 'A', 'B', 'C', 'E', 'F', nan], dtype=object)

In [4]:
credit_card_dataframe['f_121']= credit_card_dataframe['f_121'].fillna('B')
credit_card_testframe['f_121']= credit_card_testframe['f_121'].fillna('B')
credit_card_dataframe['f_121'].unique()

array(['D', 'A', 'B', 'C', 'E', 'F'], dtype=object)

In [23]:
credit_card_testframe['f_121'].unique()

array(['A', 'B', 'C', 'E', 'F', 'D'], dtype=object)

In [24]:
credit_card_dataframe['f_215'].describe()

count     4898
unique       4
top        red
freq      1294
Name: f_215, dtype: object

In [25]:
credit_card_dataframe['f_215'].unique()

array(['red', 'blue', 'orange', 'yellow', nan], dtype=object)

In [5]:
credit_card_dataframe['f_215']= credit_card_dataframe['f_215'].fillna('red')
credit_card_testframe['f_215']= credit_card_testframe['f_215'].fillna('red')

In [27]:
credit_card_dataframe['f_215'].unique()

array(['red', 'blue', 'orange', 'yellow'], dtype=object)

In [28]:
credit_card_dataframe['f_237'].describe()

count       4905
unique         3
top       Canada
freq        1677
Name: f_237, dtype: object

In [29]:
credit_card_dataframe['f_237'].unique()

array(['Canada', 'USA', 'Mexico', nan], dtype=object)

In [6]:
credit_card_dataframe['f_237']= credit_card_dataframe['f_237'].fillna('Canada')
credit_card_testframe['f_237']= credit_card_testframe['f_237'].fillna('Canada')

In [7]:
credit_card_dataframe['f_237'].unique()

array(['Canada', 'USA', 'Mexico'], dtype=object)

Converting Categorical variables into dummy variables to be passed as input to Machine Learning Algorithm. I am using Pandas.get_dummies() method, creates a dataframe with different levels in the categorical variable. f_61 has 5 levels a,b,c,d,e hence it creates 5 columns in the f_61_dummies. Dummy variable will have a value of 0 or 1.  Since we only need N-1 dummy variables ( if all N-1 variables value are equal to 0 then the Nth variable value is 1 , hence I am dropping the 1st dummy variable from the dummy variables dataframe. I have to drop the original categorical variable from the training and test dataframe before joining the new dummy dataframe with the original one. 

Transformation applied in Training dataframe has to be applied into testing dataframe too.

In [8]:
#Converting TrainFrame categorical variables to dummy variables
f_61_dummies = pd.get_dummies(credit_card_dataframe['f_61'], prefix='f_61')
f_61_dummies = f_61_dummies.drop('f_61_a',1)
credit_card_dataframe= credit_card_dataframe.drop('f_61',1)
credit_card_dataframe = credit_card_dataframe.join(f_61_dummies.ix[:,:])

f_121_dummies = pd.get_dummies(credit_card_dataframe['f_121'], prefix='f_121')
f_121_dummies = f_121_dummies.drop('f_121_A',1)
credit_card_dataframe= credit_card_dataframe.drop('f_121',1)
credit_card_dataframe = credit_card_dataframe.join(f_121_dummies.ix[:,:])

f_215_dummies = pd.get_dummies(credit_card_dataframe['f_215'], prefix='f_215')
f_215_dummies = f_215_dummies.drop('f_215_blue',1)
credit_card_dataframe= credit_card_dataframe.drop('f_215',1)
credit_card_dataframe = credit_card_dataframe.join(f_215_dummies.ix[:,:])

f_237_dummies = pd.get_dummies(credit_card_dataframe['f_237'], prefix='f_237')
f_237_dummies = f_237_dummies.drop('f_237_Canada',1)
credit_card_dataframe= credit_card_dataframe.drop('f_237',1)
credit_card_dataframe = credit_card_dataframe.join(f_237_dummies.ix[:,:])

In [9]:
#Converting TestFrame categorical variables to dummy variables
f_61_test_dummies = pd.get_dummies(credit_card_testframe['f_61'], prefix='f_61')
f_61_test_dummies = f_61_test_dummies.drop('f_61_a',1)
credit_card_testframe= credit_card_testframe.drop('f_61',1)
credit_card_testframe = credit_card_testframe.join(f_61_test_dummies.ix[:,:])

f_121_test_dummies = pd.get_dummies(credit_card_testframe['f_121'], prefix='f_121')
f_121_test_dummies = f_121_test_dummies.drop('f_121_A',1)
credit_card_testframe= credit_card_testframe.drop('f_121',1)
credit_card_testframe = credit_card_testframe.join(f_121_test_dummies.ix[:,:])

f_215_test_dummies = pd.get_dummies(credit_card_testframe['f_215'], prefix='f_215')
f_215_test_dummies = f_215_test_dummies.drop('f_215_blue',1)
credit_card_testframe= credit_card_testframe.drop('f_215',1)
credit_card_testframe = credit_card_testframe.join(f_215_test_dummies.ix[:,:])

f_237_test_dummies = pd.get_dummies(credit_card_testframe['f_237'], prefix='f_237')
f_237_test_dummies = f_237_test_dummies.drop('f_237_Canada',1)
credit_card_testframe= credit_card_testframe.drop('f_237',1)
credit_card_testframe = credit_card_testframe.join(f_237_test_dummies.ix[:,:])

Missing values in the other dataframe columns have to be handled. I am using sklearn Imputer with the strategy of fill it with Mean to fill the missing values. Imputer will give o/p in numpyarray format.

Applying the transformation in both Training and Test Dataframe.

In [10]:
from sklearn.preprocessing import Imputer

 
imp = Imputer(missing_values='NaN', strategy='mean', axis=0)
imp.fit(credit_card_dataframe)
credit_card_dataframe_imp = imp.transform(credit_card_dataframe)

imp.fit(credit_card_testframe)
credit_card_testframe_imp = imp.transform(credit_card_testframe)

#numpy.savetxt("C:/Ipython/Capitalone/Data/codetest_2083.tar/submission.csv",credit_card_testframe_imp,delimiter=",")

In [11]:
from sklearn import ensemble
import numpy
clf_et=ensemble.RandomForestRegressor(n_estimators=10,n_jobs=-1)
clf_et.fit(credit_card_dataframe_imp[0::,1::],credit_card_dataframe_imp[0::,0::])

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=10, n_jobs=-1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)

In [13]:
credit_test_predict = clf_et.predict(credit_card_testframe_imp)

In [27]:
credit_card_dataframe.head()

,target,f_0,f_1,f_2,f_3,f_4,f_5,f_6,f_7,f_8,...,f_121_B,f_121_C,f_121_D,f_121_E,f_121_F,f_215_orange,f_215_red,f_215_yellow,f_237_Mexico,f_237_USA
0,3.066056,-0.652557,0.255256,-0.615412,-1.833283,-0.735654,NaN,1.115108,-0.170707,-0.350879,...,0,0,1,0,0,0,1,0,0,0
1,-1.910473,1.178667,-0.093398,-0.555568,0.811153,-0.467931,-0.005488,-0.116258,-1.242854,1.984955,...,0,0,0,0,0,0,0,0,0,0
2,7.830711,0.180984,-0.778108,-0.919190,0.112607,0.887144,-0.761681,1.872443,-1.708934,0.134782,...,1,0,0,0,0,1,0,0,0,0
3,-2.180862,0.745228,-0.245268,-1.343348,1.163072,-0.168847,-0.150516,-1.099532,0.225346,1.223015,...,0,1,0,0,0,0,0,0,0,1
4,5.462784,1.217383,-1.323946,-0.958151,0.448290,-2.873187,-0.855653,0.602568,0.763372,0.019770,...,0,0,0,1,0,1,0,0,0,0

In [30]:
credit_card_dataframe_imp[0::,0]

array([ 3.0660556 , -1.91047271,  7.83071067, ...,  0.01333524,
        4.28962013,  0.65123395])

In [ ]:
#Random Forest Regressor implementation for prediction
#Splitting Training result set into 2 for cross validation
from sklearn.cross_validation import *
from sklearn.cross_validation import train_test_split
from sklearn.svm import SVR
from sklearn.grid_search import GridSearchCV

tuned_parameters = {'n_estimators': [25, 45, 60], 'max_depth': [None, 1, 2, 3], 'min_samples_split': [1, 2, 3] ,'max_features' : ['auto','sqrt','log2']}
X_train, X_test, y_train, y_test = train_test_split(credit_card_dataframe_imp[0::,1::],credit_card_dataframe_imp[0::,0], test_size=0.20, random_state=0)

clf = GridSearchCV(ensemble.RandomForestRegressor(n_jobs=-1), tuned_parameters, cv=10, scoring='r2')
clf.fit(X_train, y_train)
print(clf.best_estimator_)

In [ ]:
from sklearn.learning_curve import learning_curve
plot_learning_curve(clf,"Learning curve",)

In [ ]:
print(clf.best_estimator_)
print(clf.best_score_)

import pickle
s = pickle.dump(clf,"C:/Ipython/Capitalone/Data/codetest_2083.tar/randomforest_pickle.pmml")

#print(clf.grid_scores_)

In [73]:
from sklearn.metrics import r2_score
credit_test_predict = clf.predict(X_test)
score = r2_score(y_test, clf.predict(X_test))
print(score)
#numpy.savetxt("C:/Ipython/Capitalone/Data/codetest_2083.tar/submission_1.csv",credit_test_predict,delimiter=",")
#train_and_evaluate(clf_et,credit_train[0::,1::],credit_train[0::,0::])

0.547827925644

In [ ]:

feature_importance_list = list(zip(clf.feature_importances_,list(credit_card_testframe)))
feature_importance_frame = pd.DataFrame(feature_importance_list,columns=['Value','ColumnName'])

feature_importance_frame.sort(columns='Value',ascending=False)
feature_importance_frame.head(20).plot(kind='bar')

In [49]:
feature_importance_list = list(zip(clf_et.feature_importances_,list(credit_card_testframe)))
feature_importance_frame = pd.DataFrame(feature_importance_list,columns=['Value','ColumnName'])

feature_importance_frame.sort(columns='Value',ascending=False)

        Value    ColumnName
173  0.040223         f_175
203  0.021761         f_205
93   0.016056          f_94
215  0.014924         f_218
35   0.009567          f_35
253  0.005027        f_61_e
48   0.004669          f_48
80   0.004630          f_81
247  0.004582         f_251
127  0.004533         f_129
221  0.004511         f_224
167  0.004476         f_169
208  0.004440         f_210
146  0.004383         f_148
138  0.004349         f_140
51   0.004328          f_51
172  0.004306         f_174
95   0.004257          f_96
162  0.004215         f_164
218  0.004199         f_221
123  0.004174         f_125
185  0.004139         f_187
134  0.004110         f_136
197  0.004102         f_199
42   0.004100          f_42
132  0.004073         f_134
187  0.004071         f_189
15   0.004055          f_15
184  0.004053         f_186
0    0.004051           f_0
202  0.004050         f_204
68   0.004047          f_69
89   0.004033          f_90
26   0.004028          f_26
193  0.004019         f_195
136  0.004004         f_138
150  0.003991         f_152
156  0.003984         f_158
169  0.003983         f_171
143  0.003980         f_145
17   0.003978          f_17
112  0.003973         f_113
175  0.003964         f_177
227  0.003952         f_230
7    0.003951           f_7
47   0.003946          f_47
149  0.003940         f_151
60   0.003929          f_60
90   0.003925          f_91
28   0.003922          f_28
52   0.003915          f_52
56   0.003914          f_56
129  0.003905         f_131
65   0.003903          f_66
245  0.003901         f_249
163  0.003895         f_165
109  0.003892         f_110
33   0.003892          f_33
160  0.003891         f_162
71   0.003879          f_72
66   0.003872          f_67
37   0.003870          f_37
212  0.003870         f_214
38   0.003866          f_38
2    0.003865           f_2
126  0.003863         f_128
99   0.003854         f_100
217  0.003854         f_220
179  0.003849         f_181
220  0.003836         f_223
142  0.003828         f_144
45   0.003823          f_45
135  0.003820         f_137
147  0.003819         f_149
72   0.003817          f_73
53   0.003816          f_53
110  0.003816         f_111
225  0.003815         f_228
43   0.003814          f_43
84   0.003810          f_85
1    0.003807           f_1
119  0.003800         f_120
151  0.003798         f_153
97   0.003796          f_98
120  0.003795         f_122
233  0.003783         f_236
76   0.003782          f_77
232  0.003775         f_235
13   0.003775          f_13
201  0.003772         f_203
78   0.003765          f_79
12   0.003762          f_12
125  0.003759         f_127
130  0.003757         f_132
237  0.003755         f_241
131  0.003754         f_133
30   0.003753          f_30
67   0.003746          f_68
182  0.003742         f_184
101  0.003735         f_102
200  0.003732         f_202
248  0.003728         f_252
116  0.003728         f_117
194  0.003722         f_196
148  0.003718         f_150
165  0.003708         f_167
117  0.003707         f_118
152  0.003706         f_154
144  0.003701         f_146
176  0.003698         f_178
57   0.003696          f_57
9    0.003691           f_9
137  0.003689         f_139
226  0.003681         f_229
82   0.003680          f_83
91   0.003673          f_92
8    0.003671           f_8
74   0.003667          f_75
10   0.003666          f_10
204  0.003640         f_206
39   0.003640          f_39
219  0.003636         f_222
50   0.003634          f_50
49   0.003634          f_49
25   0.003623          f_25
190  0.003615         f_192
242  0.003614         f_246
224  0.003614         f_227
243  0.003595         f_247
31   0.003593          f_31
24   0.003593          f_24
145  0.003589         f_147
40   0.003587          f_40
238  0.003586         f_242
214  0.003586         f_217
5    0.003580           f_5
34   0.003575          f_34
114  0.003573         f_115
188  0.003570         f_190
21   0.003566          f_21
128  0.003559         f_130
192  0.003541         f_194
186  0.003539         f_188
158  0.003537         f_160
230  0.003534         f_233
86   0.003527          f_87
3    0.003522           f_3
41   0.003522          f_41
171  0.003518         f_173
85   0.003518          f_86
19   0.003518          f_19
64   0.003511          f_65
124  0.003501         f_126
209  0.003493         f_211
155  0.003492         f_157
75   0.003490          f_76
199  0.003489         f_201
198  0.003486         f_200
183  0.003478         f_185
29   0.003477          f_29
23   0.003476          f_23
96   0.003470          f_97
108  0.003469         f_109
46   0.003467          f_46
195  0.003466         f_197
115  0.003459         f_116
178  0.003457         f_180
105  0.003456         f_106
139  0.003445         f_141
73   0.003437          f_74
239  0.003434         f_243
92   0.003430          f_93
87   0.003426          f_88
62   0.003425          f_63
161  0.003424         f_163
235  0.003421         f_239
240  0.003419         f_244
104  0.003418         f_105
133  0.003416         f_135
249  0.003413         f_253
61   0.003412          f_62
18   0.003404          f_18
11   0.003396          f_11
228  0.003396         f_231
170  0.003389         f_172
222  0.003388         f_225
107  0.003384         f_108
229  0.003383         f_232
98   0.003373          f_99
157  0.003373         f_159
211  0.003371         f_213
213  0.003366         f_216
154  0.003362         f_156
69   0.003361          f_70
70   0.003357          f_71
196  0.003353         f_198
206  0.003343         f_208
113  0.003342         f_114
207  0.003340         f_209
168  0.003339         f_170
231  0.003338         f_234
181  0.003338         f_183
81   0.003321          f_82
83   0.003315          f_84
153  0.003300         f_155
140  0.003294         f_142
111  0.003293         f_112
54   0.003292          f_54
210  0.003281         f_212
16   0.003273          f_16
141  0.003263         f_143
164  0.003254         f_166
191  0.003254         f_193
94   0.003246          f_95
88   0.003233          f_89
58   0.003228          f_58
27   0.003228          f_27
246  0.003226         f_250
174  0.003218         f_176
166  0.003217         f_168
63   0.003196          f_64
122  0.003196         f_124
79   0.003188          f_80
32   0.003183          f_32
180  0.003179         f_182
205  0.003179         f_207
159  0.003172         f_161
59   0.003168          f_59
100  0.003150         f_101
14   0.003137          f_14
241  0.003133         f_245
106  0.003117         f_107
77   0.003115          f_78
177  0.003101         f_179
236  0.003086         f_240
44   0.003064          f_44
234  0.003052         f_238
4    0.003031           f_4
216  0.003022         f_219
6    0.003017           f_6
189  0.003013         f_191
102  0.002999         f_103
223  0.002993         f_226
103  0.002956         f_104
118  0.002956         f_119
55   0.002923          f_55
22   0.002900          f_22
20   0.002805          f_20
36   0.002755          f_36
244  0.002742         f_248
121  0.002624         f_123
251  0.000835        f_61_c
252  0.000667        f_61_d
260  0.000649     f_215_red
263  0.000646     f_237_USA
259  0.000540  f_215_orange
261  0.000536  f_215_yellow
257  0.000511       f_121_E
262  0.000486  f_237_Mexico
254  0.000468       f_121_B
256  0.000426       f_121_D
258  0.000415       f_121_F
255  0.000385       f_121_C
250  0.000321        f_61_b

In [ ]:
#SVM Regressor implementation for prediction
#Splitting Training result set into 2 for cross validation
from sklearn.cross_validation import *
from sklearn.cross_validation import train_test_split
from sklearn.svm import SVR

tuned_parameters = [{'kernel': ['rbf'], 'gamma': [0.1, 1e-2, 1e-3], 'C': [10, 100, 1000]},
                    {'kernel': ['linear'], 'C': [10, 100, 1000]},
                    {'kernel': ['poly'],'degree': [3], 'gamma': [1e-3, 1e-4], 'C': [10, 100, 1000]}]
X_train, X_test, y_train, y_test = train_test_split(credit_card_dataframe_imp[0::,1::],credit_card_dataframe_imp[0::,0], test_size=0.25, random_state=0)

svm_cv = GridSearchCV(SVR(C=1), tuned_parameters, cv=5, scoring='r2')
svm_cv.fit(X_train, y_train)
print(svm_cv.best_estimator_)
print(svm_cv.best_score_)

In [ ]:
from sklearn.metrics import r2_score
credit_test_predict = svm_cv.predict(X_test)
score = r2_score(y_test, svm_cv.predict(X_test))
print(score)

In [ ]:
def getKey(item):
    return item[0]

print(sorted(feature_importance_list, key=getKey))

In [135]:
print(zipped_list)

None

In [79]:
from sklearn.cross_validation import train_test_split
credit_train,credit_test = train_test_split(credit_card_dataframe_imp,test_size=0.2)

In [165]:
from sklearn.cross_validation import *
def train_and_evaluate(clf,X_train,Y_train):
    clf.fit(X_train,Y_train)
    print("Coefficient of determination on training set: ",clf.score(X_train,Y_train))
    cv=KFold(len(Y_train),5)
    scores = cross_val_score(clf,X_train,Y_train,cv=cv)
    print("Average Coefficient of determination using 5 fold cross validation: ",clf.score(X_train,Y_train))

AttributeError: 'numpy.ndarray' object has no attribute 'describe'